import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const kadd = Icons.add;
const kiconsearch = Icons.search;
const knotification = Icons.notifications_none_outlined;
const kplayround = Icons.play_circle_fill_outlined;
const kpauseround = Icons.pause_circle_filled_outlined;
const kplay = Icons.play_arrow;
const kpause = Icons.pause;
const knext = Icons.skip_next;
const kskipback = Icons.skip_previous;
const kfavorite = Icons.favorite;
const kfavoriteOutline = Icons.favorite_border_outlined;
const kclose = Icons.close;
const khistory = Icons.history_toggle_off;
const ksetting = CupertinoIcons.gear;
const kmoreVertical = Icons.more_vert_outlined;
const kcheck = CupertinoIcons.check_mark;
const kroundDownload = CupertinoIcons.download_circle;
const kiconshuffle = CupertinoIcons.shuffle_medium;
const kcircleplay = CupertinoIcons.play_circle_fill;
const kshare = Icons.share_outlined;
const krepeat = CupertinoIcons.arrow_counterclockwise;
const kgoback = Icons.arrow_back;
const kmenu = Icons.menu;
const ksqGrid = CupertinoIcons.square_grid_2x2_fill;
const kstars = CupertinoIcons.star;
const kstarsfilled = CupertinoIcons.star_fill;
const kLocation = Icons.location_on;
const klistdash = CupertinoIcons.list_dash;
const ksave = Icons.bookmark_border;
const kforward = CupertinoIcons.chevron_right_circle_fill;
const kbackward = CupertinoIcons.chevron_left_circle_fill;
const kDown = Icons.arrow_drop_down_rounded;
