import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const kadd = Icons.add;
const kiconsearch = Icons.search;
const knotification = Icons.notifications_none_outlined;
const kfavorite = Icons.favorite;
const kfavoriteOutline = Icons.favorite_border_outlined;
const kclose = Icons.close;
const kmoreVertical = Icons.more_vert_outlined;
const kcheck = CupertinoIcons.check_mark;
const kshare = Icons.share_outlined;
const kgoback = Icons.arrow_back;
const kmenu = Icons.menu;
const ksqGrid = CupertinoIcons.square_grid_2x2_fill;
const kstars = CupertinoIcons.star;
const kstarsfilled = CupertinoIcons.star_fill;
const kLocation = Icons.location_on;
const klistdash = CupertinoIcons.list_dash;
const ksave = Icons.bookmark_border;
const ksaved = Icons.bookmark;
const kpool = Icons.pool;
const kforward = CupertinoIcons.chevron_right_circle_fill;
const kbackward = CupertinoIcons.chevron_left_circle_fill;
const kdowncirclefilled = CupertinoIcons.chevron_down_circle_fill;
const kDown = Icons.arrow_drop_down_rounded;
const kcall = Icons.phone;
const kmail = CupertinoIcons.mail;
const kaddRound = Icons.add_circle;
const kwifi = Icons.wifi;
