final khotelname = [
  "Arizona Biltmore Hotel",
  "Bowman Hotel",
  'Buena Vista Hotel',
  "Camelback Inn",
  "CityNorth",
  "CityScape (Phoenix)",
  'cochise Hotel',
  "Copper Queen Hotel",
  "El Tovar Hotel",
  " Francisco Grande",
  "Grand Canyon Lodge",
  "Harrah's Ak-Chin Casino",
  "Hermosa Inn",
  "Hotel Congress",
  "Hotel San Carlos",
  'Hotel Valley Ho',
  'Hyatt Regency Phoenix',
  'La Posada Hotel',
  'Mondrian Hotel',
];

final kHotelNames2 = [
  "Motel Inn of San Luis Obispo",
  'Murphys Hotel',
  'National Exchange Hotel',
  'New Hotel Carquinez',
  'Padre Hotel',
  'Park Hyatt Resort Aviara',
  'Piedras Blancas Motel',
  'Pierpont Inn',
  'Pine Inn',
  'Raymond Hotel',
  'Ritz-Carlton Half Moon Bay',
  'Robinson Hotel',
  "Roy's Motel and Café",
  "San Diego Marriott Hotel and Marina",
  "San Gorgonio Inn",
  "Santa Barbara Biltmore",
  "Shutters on the Beach Hotel",
  "Southern Hotel, Perris",
  "Sovereign Hotel",
  "Stagecoach Inn",
  "Sunset Tower",
  "Superior Oil Company Building",
  "Sycamore Mineral Springs Resort",
  "Mission Inn",
  "The Lodge at Pebble Beach",
  "Thunder Valley Casino Resort",
  "U.S. Grant Hotel",
  "Venetian Court",
  "Wagon Wheel",
  "Wawona Hotel",
  "The Westin San Diego",
  "Wigwam Motel",
  "Yosemite Lodge at the Falls",
];
