final khotelname = [
  "Arizona Biltmore Hotel",
  "Bowman Hotel",
  'Buena Vista Hotel',
  "Camelback Inn",
  "CityNorth",
  "CityScape (Phoenix)",
  'cochise Hotel',
  "Copper Queen Hotel",
  "El Tovar Hotel",
  " Francisco Grande",
  "Grand Canyon Lodge",
  "Harrah's Ak-Chin Casino",
  "Hermosa Inn",
  "Hotel Congress",
  "Hotel San Carlos",
  'Hotel Valley Ho',
  'Hyatt Regency Phoenix',
  'La Posada Hotel',
  'Mondrian Hotel',
];
